## Criterios de diseño sísmico

La falla de instalaciones mineras críticas sometidas a movimientos sísmicos fuertes, puede tener consecuencias muy graves para la vida y el medio ambiente y el diseño sísmico de estas instalaciones debe asegurar en general una muy baja probabilidad de falla en todas las etapas de vida útil de la mina, desde la construcción, la operación y el cierre definitivo de la instalación. 

El estado de la práctica actual del diseño sísmico de infraestructura minera, se basa en criterios de desempeño establecidos tanto para las etapas de operación como así también para las etapas posteriores al cierre de la mina. Las etapas de operación comprenden todas las fases de construcción y explotación, los períodos de cese temporal de las operaciones y la fase de cierre (fase de transición al post-cierre, también denominada cierre de cuidado activo). En las etapas de post-cierre tambien denominadas etapas de cuidado pasivo, las instalaciones críticas que no pueden desmantelarse, deben estar configuradas para sobrevivir a un estado perpetuo y estarán sometidas la ocurrencia de sismos con tiempo de exposición muy largo. 

Los criterios de desempeño en las etapas de post-cierre, se enfocan en los **estados últimos de servicio (ULS) ** asociados a eventos sísmicos de máxima intensidad (muy raros). Para las etapas de operación, los criterios de desempeño se basan en los **estados límite de servicio (SLS)** asociados a eventos sísmicos de baja intensidad para el cual las instalaciones deben mantenerse operativas, y cualquier daño incurrido debe ser fácilmente reparable luego de un evento sísmico. 

Los terremotos de diseño pueden seleccionarse utilizando un enfoque determinista basado exclusivamente en las consecuencias de la falla, o enfoques probabilísticos basados en el riesgo asociado de la falla. El enfoque probabilístico evalúa la demanda sísmica de una amplia gama de sismos para satisfacer un criterio de riesgo tolerable basado en las probabilidades de falla de la instalación. El planteo determinístico por su parte, establece una probabilidad anual de excedencia (período de retorno) para un sismo máximo de diseño, teniendo en cuenta las consecuencias económicas y medio ambientales de una falla (pérdida de estabilidad) de la instalación.

Las recomendaciones de diseño que conforman el estado actual de la práctica, tales como @gistm2020 y @ANC19 se basan en el enfoque determinístico y establecen probabilidades anuales de excedencia dependientes del grado de consecuencias de una potencial falla durante un evento sísmico. Estas recomendaciones y guías de diseño prescriben criterios de desempeño y niveles de servicio (sismos de diseño) para atender tanto la seguridad a la falla como la capacidad de servicio. Las consecuencias de la falla suelen clasificarse según una escala basada en factores medioambientales, sociales, económicos y humanos. 
